version: "3.8"

services:

    app:
        build:
            target: php_dev
            dockerfile: ./Dockerfile
        expose:
            - "9010"
        depends_on:
            - db
            - redis
        restart: unless-stopped
        networks:
            - app_net

    nginx:
        image: nginx:alpine
        depends_on:
            - app
        restart: unless-stopped
        ports:
            - "${HTTP_PORT:-3080}:80"
            - "${HTTPS_PORT:-443}:443"
        environment:
            NGINX_HOST: ${NGINX_HOST:-localhost}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        volumes:
            - ./:/srv/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template
        networks:
            - app_net
            - default

    db:
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
        ports:
            - "5432:5432"
        volumes:
            - ./docker/db:/var/lib/postgresql/data:rw
        networks:
            - app_net

    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - cache:/data
        networks:
            - app_net

networks:
    app_net:
        driver: bridge

volumes:
    pgadmin:
        driver: local
    cache:
        driver: local
