version: "3.8"

services:

    app:
        volumes:
            - ./:/srv/app:rw,cached
        environment:
            APP_ENV: dev

    nginx:
        volumes:
            - ./public:/srv/app/public:ro
