version: "3.8"

services:

    app:
        volumes:
            - ./:/srv/app:rw,cached
#            - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
        environment:
            APP_ENV: dev

    nginx:
        volumes:
            - ./public:/srv/app/public:ro
